# Generated by Django 4.2.22 on 2025-06-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Funcionario', 'verbose_name_plural': 'Funcionarios'},
        ),
        migrations.AlterModelOptions(
            name='facecollection',
            options={'verbose_name': 'Coleta de Face', 'verbose_name_plural': 'Coleta de Faces'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Treinamento', 'verbose_name_plural': 'Treinamentos'},
        ),
    ]
