# Generated by Django 4.2.22 on 2025-06-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_employeeregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeregistration',
            options={'verbose_name': 'Registro de Funcionário', 'verbose_name_plural': 'Registro de Funcionários'},
        ),
    ]
